/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AiMatchRouteImport } from './routes/ai-match'
import { Route as EmployerRouteImport } from './routes/_employer'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeBuilderIndexRouteImport } from './routes/resume-builder.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ResumeBuilderResumeIdRouteImport } from './routes/resume-builder.$resumeId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as EmployerEmployerIndexRouteImport } from './routes/_employer.employer.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId.apply'
import { Route as EmployerEmployerSettingsRouteImport } from './routes/_employer.employer.settings'
import { Route as EmployerEmployerDashboardRouteImport } from './routes/_employer.employer.dashboard'
import { Route as EmployerEmployerCompanyRouteImport } from './routes/_employer.employer.company'
import { Route as EmployerEmployerAiScreeningRouteImport } from './routes/_employer.employer.ai-screening'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as EmployerEmployerJobsIndexRouteImport } from './routes/_employer.employer.jobs.index'
import { Route as EmployerEmployerApplicationsIndexRouteImport } from './routes/_employer.employer.applications.index'
import { Route as EmployerEmployerJobsNewRouteImport } from './routes/_employer.employer.jobs.new'
import { Route as EmployerEmployerApplicationsApplicationIdRouteImport } from './routes/_employer.employer.applications.$applicationId'
import { Route as EmployerEmployerJobsJobIdIndexRouteImport } from './routes/_employer.employer.jobs.$jobId.index'
import { Route as EmployerEmployerJobsJobIdEditRouteImport } from './routes/_employer.employer.jobs.$jobId.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchRoute = AiMatchRouteImport.update({
  id: '/ai-match',
  path: '/ai-match',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/_employer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderIndexRoute = ResumeBuilderIndexRouteImport.update({
  id: '/resume-builder/',
  path: '/resume-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const ResumeBuilderResumeIdRoute = ResumeBuilderResumeIdRouteImport.update({
  id: '/resume-builder/$resumeId',
  path: '/resume-builder/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const EmployerEmployerIndexRoute = EmployerEmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => EmployerRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const EmployerEmployerSettingsRoute =
  EmployerEmployerSettingsRouteImport.update({
    id: '/employer/settings',
    path: '/employer/settings',
    getParentRoute: () => EmployerRoute,
  } as any)
const EmployerEmployerDashboardRoute =
  EmployerEmployerDashboardRouteImport.update({
    id: '/employer/dashboard',
    path: '/employer/dashboard',
    getParentRoute: () => EmployerRoute,
  } as any)
const EmployerEmployerCompanyRoute = EmployerEmployerCompanyRouteImport.update({
  id: '/employer/company',
  path: '/employer/company',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerEmployerAiScreeningRoute =
  EmployerEmployerAiScreeningRouteImport.update({
    id: '/employer/ai-screening',
    path: '/employer/ai-screening',
    getParentRoute: () => EmployerRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const EmployerEmployerJobsIndexRoute =
  EmployerEmployerJobsIndexRouteImport.update({
    id: '/employer/jobs/',
    path: '/employer/jobs/',
    getParentRoute: () => EmployerRoute,
  } as any)
const EmployerEmployerApplicationsIndexRoute =
  EmployerEmployerApplicationsIndexRouteImport.update({
    id: '/employer/applications/',
    path: '/employer/applications/',
    getParentRoute: () => EmployerRoute,
  } as any)
const EmployerEmployerJobsNewRoute = EmployerEmployerJobsNewRouteImport.update({
  id: '/employer/jobs/new',
  path: '/employer/jobs/new',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerEmployerApplicationsApplicationIdRoute =
  EmployerEmployerApplicationsApplicationIdRouteImport.update({
    id: '/employer/applications/$applicationId',
    path: '/employer/applications/$applicationId',
    getParentRoute: () => EmployerRoute,
  } as any)
const EmployerEmployerJobsJobIdIndexRoute =
  EmployerEmployerJobsJobIdIndexRouteImport.update({
    id: '/employer/jobs/$jobId/',
    path: '/employer/jobs/$jobId/',
    getParentRoute: () => EmployerRoute,
  } as any)
const EmployerEmployerJobsJobIdEditRoute =
  EmployerEmployerJobsJobIdEditRouteImport.update({
    id: '/employer/jobs/$jobId/edit',
    path: '/employer/jobs/$jobId/edit',
    getParentRoute: () => EmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-match': typeof AiMatchRoute
  '/ai-tools': typeof AiToolsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/saved-jobs': typeof SavedJobsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/resume-builder/$resumeId': typeof ResumeBuilderResumeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resume-builder/': typeof ResumeBuilderIndexRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/employer/ai-screening': typeof EmployerEmployerAiScreeningRoute
  '/employer/company': typeof EmployerEmployerCompanyRoute
  '/employer/dashboard': typeof EmployerEmployerDashboardRoute
  '/employer/settings': typeof EmployerEmployerSettingsRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/employer/': typeof EmployerEmployerIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/employer/applications/$applicationId': typeof EmployerEmployerApplicationsApplicationIdRoute
  '/employer/jobs/new': typeof EmployerEmployerJobsNewRoute
  '/employer/applications/': typeof EmployerEmployerApplicationsIndexRoute
  '/employer/jobs/': typeof EmployerEmployerJobsIndexRoute
  '/employer/jobs/$jobId/edit': typeof EmployerEmployerJobsJobIdEditRoute
  '/employer/jobs/$jobId/': typeof EmployerEmployerJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-match': typeof AiMatchRoute
  '/ai-tools': typeof AiToolsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/resume-builder/$resumeId': typeof ResumeBuilderResumeIdRoute
  '/jobs': typeof JobsIndexRoute
  '/resume-builder': typeof ResumeBuilderIndexRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/employer/ai-screening': typeof EmployerEmployerAiScreeningRoute
  '/employer/company': typeof EmployerEmployerCompanyRoute
  '/employer/dashboard': typeof EmployerEmployerDashboardRoute
  '/employer/settings': typeof EmployerEmployerSettingsRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin': typeof AdminAdminIndexRoute
  '/employer': typeof EmployerEmployerIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/employer/applications/$applicationId': typeof EmployerEmployerApplicationsApplicationIdRoute
  '/employer/jobs/new': typeof EmployerEmployerJobsNewRoute
  '/employer/applications': typeof EmployerEmployerApplicationsIndexRoute
  '/employer/jobs': typeof EmployerEmployerJobsIndexRoute
  '/employer/jobs/$jobId/edit': typeof EmployerEmployerJobsJobIdEditRoute
  '/employer/jobs/$jobId': typeof EmployerEmployerJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_employer': typeof EmployerRouteWithChildren
  '/ai-match': typeof AiMatchRoute
  '/ai-tools': typeof AiToolsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/saved-jobs': typeof SavedJobsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/resume-builder/$resumeId': typeof ResumeBuilderResumeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resume-builder/': typeof ResumeBuilderIndexRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_employer/employer/ai-screening': typeof EmployerEmployerAiScreeningRoute
  '/_employer/employer/company': typeof EmployerEmployerCompanyRoute
  '/_employer/employer/dashboard': typeof EmployerEmployerDashboardRoute
  '/_employer/employer/settings': typeof EmployerEmployerSettingsRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_employer/employer/': typeof EmployerEmployerIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/_employer/employer/applications/$applicationId': typeof EmployerEmployerApplicationsApplicationIdRoute
  '/_employer/employer/jobs/new': typeof EmployerEmployerJobsNewRoute
  '/_employer/employer/applications/': typeof EmployerEmployerApplicationsIndexRoute
  '/_employer/employer/jobs/': typeof EmployerEmployerJobsIndexRoute
  '/_employer/employer/jobs/$jobId/edit': typeof EmployerEmployerJobsJobIdEditRoute
  '/_employer/employer/jobs/$jobId/': typeof EmployerEmployerJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-match'
    | '/ai-tools'
    | '/applications'
    | '/dashboard'
    | '/jobs'
    | '/saved-jobs'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/jobs/$jobId'
    | '/resume-builder/$resumeId'
    | '/jobs/'
    | '/resume-builder/'
    | '/admin/users'
    | '/employer/ai-screening'
    | '/employer/company'
    | '/employer/dashboard'
    | '/employer/settings'
    | '/jobs/$jobId/apply'
    | '/admin/'
    | '/employer/'
    | '/jobs/$jobId/'
    | '/employer/applications/$applicationId'
    | '/employer/jobs/new'
    | '/employer/applications/'
    | '/employer/jobs/'
    | '/employer/jobs/$jobId/edit'
    | '/employer/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-match'
    | '/ai-tools'
    | '/applications'
    | '/dashboard'
    | '/saved-jobs'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/resume-builder/$resumeId'
    | '/jobs'
    | '/resume-builder'
    | '/admin/users'
    | '/employer/ai-screening'
    | '/employer/company'
    | '/employer/dashboard'
    | '/employer/settings'
    | '/jobs/$jobId/apply'
    | '/admin'
    | '/employer'
    | '/jobs/$jobId'
    | '/employer/applications/$applicationId'
    | '/employer/jobs/new'
    | '/employer/applications'
    | '/employer/jobs'
    | '/employer/jobs/$jobId/edit'
    | '/employer/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_employer'
    | '/ai-match'
    | '/ai-tools'
    | '/applications'
    | '/dashboard'
    | '/jobs'
    | '/saved-jobs'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/jobs/$jobId'
    | '/resume-builder/$resumeId'
    | '/jobs/'
    | '/resume-builder/'
    | '/_admin/admin/users'
    | '/_employer/employer/ai-screening'
    | '/_employer/employer/company'
    | '/_employer/employer/dashboard'
    | '/_employer/employer/settings'
    | '/jobs/$jobId/apply'
    | '/_admin/admin/'
    | '/_employer/employer/'
    | '/jobs/$jobId/'
    | '/_employer/employer/applications/$applicationId'
    | '/_employer/employer/jobs/new'
    | '/_employer/employer/applications/'
    | '/_employer/employer/jobs/'
    | '/_employer/employer/jobs/$jobId/edit'
    | '/_employer/employer/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployerRoute: typeof EmployerRouteWithChildren
  AiMatchRoute: typeof AiMatchRoute
  AiToolsRoute: typeof AiToolsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRouteWithChildren
  SavedJobsRoute: typeof SavedJobsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ResumeBuilderResumeIdRoute: typeof ResumeBuilderResumeIdRoute
  ResumeBuilderIndexRoute: typeof ResumeBuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-match': {
      id: '/ai-match'
      path: '/ai-match'
      fullPath: '/ai-match'
      preLoaderRoute: typeof AiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employer': {
      id: '/_employer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder/': {
      id: '/resume-builder/'
      path: '/resume-builder'
      fullPath: '/resume-builder/'
      preLoaderRoute: typeof ResumeBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/resume-builder/$resumeId': {
      id: '/resume-builder/$resumeId'
      path: '/resume-builder/$resumeId'
      fullPath: '/resume-builder/$resumeId'
      preLoaderRoute: typeof ResumeBuilderResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/_employer/employer/': {
      id: '/_employer/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerEmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/_employer/employer/settings': {
      id: '/_employer/employer/settings'
      path: '/employer/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof EmployerEmployerSettingsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/dashboard': {
      id: '/_employer/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerEmployerDashboardRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/company': {
      id: '/_employer/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof EmployerEmployerCompanyRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/ai-screening': {
      id: '/_employer/employer/ai-screening'
      path: '/employer/ai-screening'
      fullPath: '/employer/ai-screening'
      preLoaderRoute: typeof EmployerEmployerAiScreeningRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_employer/employer/jobs/': {
      id: '/_employer/employer/jobs/'
      path: '/employer/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof EmployerEmployerJobsIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/applications/': {
      id: '/_employer/employer/applications/'
      path: '/employer/applications'
      fullPath: '/employer/applications/'
      preLoaderRoute: typeof EmployerEmployerApplicationsIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/jobs/new': {
      id: '/_employer/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerEmployerJobsNewRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/applications/$applicationId': {
      id: '/_employer/employer/applications/$applicationId'
      path: '/employer/applications/$applicationId'
      fullPath: '/employer/applications/$applicationId'
      preLoaderRoute: typeof EmployerEmployerApplicationsApplicationIdRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/jobs/$jobId/': {
      id: '/_employer/employer/jobs/$jobId/'
      path: '/employer/jobs/$jobId'
      fullPath: '/employer/jobs/$jobId/'
      preLoaderRoute: typeof EmployerEmployerJobsJobIdIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_employer/employer/jobs/$jobId/edit': {
      id: '/_employer/employer/jobs/$jobId/edit'
      path: '/employer/jobs/$jobId/edit'
      fullPath: '/employer/jobs/$jobId/edit'
      preLoaderRoute: typeof EmployerEmployerJobsJobIdEditRouteImport
      parentRoute: typeof EmployerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployerRouteChildren {
  EmployerEmployerAiScreeningRoute: typeof EmployerEmployerAiScreeningRoute
  EmployerEmployerCompanyRoute: typeof EmployerEmployerCompanyRoute
  EmployerEmployerDashboardRoute: typeof EmployerEmployerDashboardRoute
  EmployerEmployerSettingsRoute: typeof EmployerEmployerSettingsRoute
  EmployerEmployerIndexRoute: typeof EmployerEmployerIndexRoute
  EmployerEmployerApplicationsApplicationIdRoute: typeof EmployerEmployerApplicationsApplicationIdRoute
  EmployerEmployerJobsNewRoute: typeof EmployerEmployerJobsNewRoute
  EmployerEmployerApplicationsIndexRoute: typeof EmployerEmployerApplicationsIndexRoute
  EmployerEmployerJobsIndexRoute: typeof EmployerEmployerJobsIndexRoute
  EmployerEmployerJobsJobIdEditRoute: typeof EmployerEmployerJobsJobIdEditRoute
  EmployerEmployerJobsJobIdIndexRoute: typeof EmployerEmployerJobsJobIdIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerEmployerAiScreeningRoute: EmployerEmployerAiScreeningRoute,
  EmployerEmployerCompanyRoute: EmployerEmployerCompanyRoute,
  EmployerEmployerDashboardRoute: EmployerEmployerDashboardRoute,
  EmployerEmployerSettingsRoute: EmployerEmployerSettingsRoute,
  EmployerEmployerIndexRoute: EmployerEmployerIndexRoute,
  EmployerEmployerApplicationsApplicationIdRoute:
    EmployerEmployerApplicationsApplicationIdRoute,
  EmployerEmployerJobsNewRoute: EmployerEmployerJobsNewRoute,
  EmployerEmployerApplicationsIndexRoute:
    EmployerEmployerApplicationsIndexRoute,
  EmployerEmployerJobsIndexRoute: EmployerEmployerJobsIndexRoute,
  EmployerEmployerJobsJobIdEditRoute: EmployerEmployerJobsJobIdEditRoute,
  EmployerEmployerJobsJobIdIndexRoute: EmployerEmployerJobsJobIdIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

interface JobsJobIdRouteChildren {
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployerRoute: EmployerRouteWithChildren,
  AiMatchRoute: AiMatchRoute,
  AiToolsRoute: AiToolsRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRouteWithChildren,
  SavedJobsRoute: SavedJobsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ResumeBuilderResumeIdRoute: ResumeBuilderResumeIdRoute,
  ResumeBuilderIndexRoute: ResumeBuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
