spring:
  application:
    name: job-portal-application-service

  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#    producer:
#      key-serializer:

logging:
  level:
    root: INFO
    com.hope.job: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application-service.log