spring:
  application:
    name: job-portal-job-service

  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO
    com.hope.job: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/job-service.log